version: "3"

services:

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./.data/neo4j:/var/lib/neo4j/data
    environment:
      NEO4J_AUTH: neo4j/1234
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1024m
      NEO4J_dbms_memory_pagecache_size: 1024m
      NEO4J_dbms_tx__log_rotation_size: 1m
    healthcheck:
      test: ["CMD-SHELL", "neo4j status | grep running"]
      interval: 10s
      timeout: 5s
      retries: 10

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - logger.level=WARN
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=abcd
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./.data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_URL=http://es:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=abcd
