version: "3"

services:
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/var/lib/neo4j/data
    environment:
      NEO4J_AUTH: neo4j/1234
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1024m
      NEO4J_dbms_memory_pagecache_size: 1024m
      NEO4J_dbms_tx__log_rotation_size: 1m
    healthcheck:
      test: ["CMD-SHELL", "neo4j status | grep running"]
      interval: 10s
      timeout: 5s
      retries: 10
